# Copyright Todd LLC, All rights reserved

name: ✨ Feature Request
description: Open a feature request issue
labels: ['feat']

body:
  - type: textarea
    attributes:
      label: Open a feature request issue
      placeholder: |
        Please describe the problem this feature solves, how this feature intends to solve it, any additional resources, and any caveats (performance issues, etc.)
