# Copyright Todd LLC, All rights reserved

name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - Performance Improvement
        - Accessibility
        - Internationalization
        - New Component
        - API/Backend
        - Developer Experience
        - SEO/Marketing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow

  - type: checkboxes
    id: considerations
    attributes:
      label: Implementation Considerations
      description: Please check any that apply to your feature request
      options:
        - label: This feature should support multiple languages (i18n)
        - label: This feature should be accessible (WCAG compliant)
        - label: This feature should work on mobile devices
        - label: This feature may require new dependencies
        - label: This feature may impact performance

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, examples, or references to help explain the feature
      placeholder: Drag and drop images, paste URLs, or describe examples...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any additional details...
