// Copyright © Todd Agriscience, Inc. All rights reserved.

import { PDFDocument, StandardFonts, rgb, type PDFFont } from 'pdf-lib';

/** Inputs needed to render an offer letter. */
export interface OfferLetterInput {
  /** Full legal name of the hiree */
  name: string;
  /** Mailing address of the hiree; newlines are preserved as separate lines */
  address: string;
  /** Employment start date, ISO `YYYY-MM-DD` */
  startDate: string;
  /** Employment end date, ISO `YYYY-MM-DD` */
  endDate: string;
}

/** US Letter, in PDF points */
const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 72;
const BODY_SIZE = 11;
const LINE_HEIGHT = 16;
const PARAGRAPH_GAP = 10;

/**
 * Formats an ISO `YYYY-MM-DD` date as a long-form US date, e.g. "September 15, 2026".
 * Parses in UTC so the rendered day never shifts with the server's timezone.
 */
function formatLongDate(isoDate: string): string {
  const [year, month, day] = isoDate.split('-').map(Number);
  return new Date(Date.UTC(year, month - 1, day)).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

/**
 * Greedily wraps text so no line is wider than `maxWidth` at the given size.
 */
function wrapText(
  text: string,
  font: PDFFont,
  size: number,
  maxWidth: number
): string[] {
  const lines: string[] = [];
  for (const paragraph of text.split('\n')) {
    let current = '';
    for (const word of paragraph.split(/\s+/).filter(Boolean)) {
      const candidate = current ? `${current} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        current = candidate;
      } else {
        if (current) lines.push(current);
        current = word;
      }
    }
    lines.push(current);
  }
  return lines;
}

/**
 * Renders a placeholder offer letter as a single-page PDF.
 *
 * The letter body is test copy — it exists so the end-to-end form → PDF →
 * download flow can be exercised before the real template is written.
 *
 * @param input - Hiree details to merge into the letter
 * @returns The encoded PDF bytes
 */
export async function buildOfferLetterPdf(
  input: OfferLetterInput
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`Offer Letter - ${input.name}`);
  pdf.setAuthor('Todd Agriscience, Inc.');

  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const maxWidth = PAGE_WIDTH - MARGIN * 2;
  const black = rgb(0, 0, 0);

  let y = PAGE_HEIGHT - MARGIN;

  const writeLines = (lines: string[], font: PDFFont, size = BODY_SIZE) => {
    for (const line of lines) {
      page.drawText(line, { x: MARGIN, y, size, font, color: black });
      y -= LINE_HEIGHT;
    }
  };
  const writeParagraph = (text: string, font: PDFFont = regular) => {
    writeLines(wrapText(text, font, BODY_SIZE, maxWidth), font);
    y -= PARAGRAPH_GAP;
  };

  const startDate = formatLongDate(input.startDate);
  const endDate = formatLongDate(input.endDate);
  const today = new Date().toISOString().slice(0, 10);

  writeLines(['Todd Agriscience, Inc.'], bold, 14);
  y -= PARAGRAPH_GAP;
  writeParagraph(formatLongDate(today));

  writeParagraph([input.name, input.address].join('\n'));

  writeParagraph(`Dear ${input.name},`);
  writeParagraph(
    `We are pleased to offer you a position with Todd Agriscience, Inc. Your employment will begin on ${startDate} and is expected to conclude on ${endDate}.`
  );
  writeParagraph(
    'This is a test offer letter generated by the internal dashboard. The final letter template, compensation details, and terms of employment will replace this placeholder copy.'
  );
  writeParagraph(
    'Please sign and return a copy of this letter to confirm your acceptance. We look forward to working with you.'
  );

  writeParagraph('Sincerely,');
  y -= LINE_HEIGHT * 2;
  writeLines(['Todd Agriscience, Inc.'], regular);

  return pdf.save();
}
