// Copyright © Todd Agriscience, Inc. All rights reserved.

export interface LegalPageLine {
  /** Text rendered on the legal page. */
  text: string;
  /** Horizontal position in PDF points. */
  x: number;
  /** Distance from the top of the page in PDF points. */
  top: number;
  /** Font size in PDF points. */
  size: number;
}

export interface LegalPageRule {
  /** Horizontal start position in PDF points. */
  x0: number;
  /** Horizontal end position in PDF points. */
  x1: number;
  /** Distance from the top of the page in PDF points. */
  top: number;
  /** Trim the rule to the width of the matching full-line heading. */
  fitToText?: boolean;
}

export interface LegalPage {
  /** Searchable text lines copied from the approved reference packet. */
  lines: LegalPageLine[];
  /** Underlines present in the approved reference packet. */
  rules: LegalPageRule[];
}

/**
 * Fixed legal pages 3-10 from the approved offer packet.
 *
 * Audit identifiers and barcode artwork from the reference are intentionally
 * excluded. Coordinates are expressed from the top-left of a US Letter page.
 */
export const LEGAL_PAGES: LegalPage[] = [
  {
    lines: [
      {
        text: 'Confidentiality and Intellectual Property Agreement',
        x: 43.2,
        top: 47.12,
        size: 8,
      },
      {
        text: 'As a condition of my becoming employed by Todd Agriscience, Inc. and any of its current or future subsidiaries, affiliates, successors or',
        x: 43.2,
        top: 70.12,
        size: 8,
      },
      {
        text: 'assigns (together, “Todd”, “our", “us", “we” or “company"), and in consideration of my employment with Todd, the receipt of Confidential',
        x: 43.2,
        top: 81.62,
        size: 8,
      },
      {
        text: 'Information (as defined below) while associated with Todd, and other good and valuable consideration, the receipt and sufficiency of which',
        x: 43.2,
        top: 93.12,
        size: 8,
      },
      {
        text: 'are hereby acknowledged, I hereby agree to the following:',
        x: 43.2,
        top: 104.62,
        size: 8,
      },
      {
        text: 'ELIGIBILITY',
        x: 43.2,
        top: 127.62,
        size: 8,
      },
      {
        text: 'This Confidentiality and Intellectual Property Agreement (this “Agreement”) will apply to my current and past employment relationship with',
        x: 43.2,
        top: 150.62,
        size: 8,
      },
      {
        text: 'Todd. It also includes other entities formed for the benefit of, or controlled by, me, that has been designated an “Eligible Employee” by Todd,',
        x: 43.2,
        top: 162.12,
        size: 8,
      },
      {
        text: 'including artificial intelligence model communication history with remembering ability. I agree that this Agreement will also apply to such',
        x: 43.2,
        top: 173.62,
        size: 8,
      },
      {
        text: 'later employment or consulting relationship, unless Todd and I otherwise agree in writing.',
        x: 43.2,
        top: 185.12,
        size: 8,
      },
      {
        text: 'APPLICABILITY TO PAST ACTIVITIES',
        x: 43.2,
        top: 208.12,
        size: 8,
      },
      {
        text: 'Todd and I acknowledge that I may have performed work, activities, services or made efforts on behalf of or for the benefit of Todd, or related',
        x: 43.2,
        top: 231.12,
        size: 8,
      },
      {
        text: 'to the current or prospective business of Todd in anticipation of my involvement with Todd, that would have been within the scope of my',
        x: 43.2,
        top: 242.62,
        size: 8,
      },
      {
        text: 'duties under this agreement if performed during the term of this Agreement, for a period of time prior to the Effective Date of this Agreement',
        x: 43.2,
        top: 254.12,
        size: 8,
      },
      {
        text: '(the “Prior Period”). Accordingly, if and to the extent that, during the Prior Period: (i) I received access to any information from or on behalf of',
        x: 43.2,
        top: 265.62,
        size: 8,
      },
      {
        text: 'Todd that would have been Confidential Information (as defined below) if I received access to such information during the term of this',
        x: 43.2,
        top: 277.12,
        size: 8,
      },
      {
        text: 'Agreement; or (ii) I (a) conceived, created, authored, invented, developed or reduced to practice any item (including any intellectual property',
        x: 43.2,
        top: 288.62,
        size: 8,
      },
      {
        text: 'rights with respect thereto) on behalf of or for the benefit of Todd, or related to the current or prospective business of Todd in anticipation of',
        x: 43.2,
        top: 300.12,
        size: 8,
      },
      {
        text: 'my involvement with Todd, that would have been an Invention (as defined below) if conceived, created, authored, invented, developed or',
        x: 43.2,
        top: 311.62,
        size: 8,
      },
      {
        text: 'reduced to practice during the term of this Agreement; or (b) incorporated into any such item any pre-existing invention, improvement,',
        x: 43.2,
        top: 323.12,
        size: 8,
      },
      {
        text: 'development, concept, discovery or other proprietary information that would have been a Prior Invention (as defined below) if incorporated',
        x: 43.2,
        top: 334.62,
        size: 8,
      },
      {
        text: 'into such item during the term of this Agreement; then any such information shall be deemed “Confidential Information” hereunder and any',
        x: 43.2,
        top: 346.12,
        size: 8,
      },
      {
        text: 'such item shall be deemed an “Invention” or “Prior Invention” hereunder, and this Agreement shall apply to such activities, information or item',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'as if disclosed, conceived, created, authored, invented, developed or reduced to practice during the term of this Agreement.',
        x: 43.2,
        top: 369.12,
        size: 8,
      },
      {
        text: 'PROTECTION OF INFORMATION',
        x: 43.2,
        top: 392.12,
        size: 8,
      },
      {
        text: 'I understand that during the Relationship, Todd intends to provide me with certain information, including Confidential Information (as defined',
        x: 43.2,
        top: 415.12,
        size: 8,
      },
      {
        text: 'below), without which I would not be able to perform my duties to Todd. At all times during the term of the Relationship and thereafter, I shall',
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: 'hold in strictest confidence, and not use, except for the benefit of Todd to the extent necessary to perform my obligations to Todd under the',
        x: 43.2,
        top: 438.12,
        size: 8,
      },
      {
        text: 'Relationship, and not disclose to any person, firm, corporation or other entity, without written authorization from Todd in each instance, any',
        x: 43.2,
        top: 449.62,
        size: 8,
      },
      {
        text: 'Confidential Information that I obtain, access or create during the term of the Relationship, whether or not during working hours, until such',
        x: 43.2,
        top: 461.12,
        size: 8,
      },
      {
        text: 'Confidential Information becomes publicly and widely known and made generally available through no wrongful act of mine or of others who',
        x: 43.2,
        top: 472.62,
        size: 8,
      },
      {
        text: 'were under confidentiality obligations as to the item or items involved. I shall not make copies of such Confidential Information except as',
        x: 43.2,
        top: 484.12,
        size: 8,
      },
      {
        text: 'authorized by Todd or in the ordinary course of my obligations to Todd under the Relationship. I believe that the public availability of such',
        x: 43.2,
        top: 495.62,
        size: 8,
      },
      {
        text: 'information could lead to unwarranted inferences about the activities of Todd and could put Todd at a competitive disadvantage.',
        x: 43.2,
        top: 507.12,
        size: 8,
      },
      {
        text: 'CONFIDENTIAL INFORMATION',
        x: 43.2,
        top: 530.12,
        size: 8,
      },
      {
        text: 'I understand that “Confidential Information” means any and all information and physical manifestations disclosed by Todd and thereof not',
        x: 43.2,
        top: 553.12,
        size: 8,
      },
      {
        text: 'generally known or available outside Todd and information and physical manifestations thereof entrusted to Todd in confidence by third',
        x: 43.2,
        top: 564.62,
        size: 8,
      },
      {
        text: 'parties, whether or not such information is confidential, proprietary, patentable, copyrightable or otherwise legally protectable, or that by its',
        x: 43.2,
        top: 576.12,
        size: 8,
      },
      {
        text: 'nature would reasonably be considered confidential or proprietary. Confidential Information includes, without limitation: (i) Todd Inventions',
        x: 43.2,
        top: 587.62,
        size: 8,
      },
      {
        text: '(as defined below); and (ii) technical data, trade secrets, know-how, research, product or service ideas or plans, software codes and designs',
        x: 43.2,
        top: 599.12,
        size: 8,
      },
      {
        text: '(including the system architectures), algorithms, developments, inventions, patent applications, laboratory notebooks, processes, formulas,',
        x: 43.2,
        top: 610.62,
        size: 8,
      },
      {
        text: 'techniques, biological materials, mask works, engineering designs and drawings, hardware configuration information, agreements with third',
        x: 43.2,
        top: 622.12,
        size: 8,
      },
      {
        text: 'parties, lists of, or information relating to, employees and consultants of Todd (including, but not limited to, the names, contact information,',
        x: 43.2,
        top: 633.62,
        size: 8,
      },
      {
        text: 'jobs, compensation, and expertise of such employees and consultants), lists of, or information relating to, suppliers and clients (including, but',
        x: 43.2,
        top: 645.12,
        size: 8,
      },
      {
        text: 'not limited to, clients of Todd on whom I called or with whom I became acquainted during the Relationship), price lists, pricing methodologies,',
        x: 43.2,
        top: 656.62,
        size: 8,
      },
      {
        text: 'cost data, market share data, marketing plans, licenses, contract information, business plans, financial forecasts, historical financial data,',
        x: 43.2,
        top: 668.12,
        size: 8,
      },
      {
        text: 'budgets or other business information disclosed to me by Todd either directly or indirectly, whether in writing, electronically, orally, or by',
        x: 43.2,
        top: 679.62,
        size: 8,
      },
      {
        text: 'observation.',
        x: 43.2,
        top: 691.12,
        size: 8,
      },
      {
        text: 'THIRD PARTY INFORMATION',
        x: 43.2,
        top: 714.12,
        size: 8,
      },
    ],
    rules: [
      {
        x0: 63.09,
        x1: 107.34,
        top: 271.84,
      },
    ],
  },
  {
    lines: [
      {
        text: 'My agreements are intended to be for the benefit of Todd and any third party that has entrusted information or physical material to Todd in',
        x: 43.2,
        top: 47.12,
        size: 8,
      },
      {
        text: 'confidence. During the term of the Relationship and thereafter, I will not improperly use or disclose to Todd any confidential, proprietary or',
        x: 43.2,
        top: 58.62,
        size: 8,
      },
      {
        text: 'secret information of my former employer(s) or any other person, and I will not bring any such information onto Todd’s property or place of',
        x: 43.2,
        top: 70.12,
        size: 8,
      },
      {
        text: 'business.',
        x: 43.2,
        top: 81.62,
        size: 8,
      },
      {
        text: 'OTHER RIGHTS',
        x: 43.2,
        top: 104.62,
        size: 8,
      },
      {
        text: 'This Agreement is intended to supplement, and not to supersede, any rights Todd may have in law or equity with respect to the protection of',
        x: 43.2,
        top: 127.62,
        size: 8,
      },
      {
        text: 'trade secrets or confidential or proprietary information.',
        x: 43.2,
        top: 139.12,
        size: 8,
      },
      {
        text: 'U.S. DEFEND TRADE SECRETS ACT',
        x: 43.2,
        top: 162.12,
        size: 8,
      },
      {
        text: 'Notwithstanding the foregoing, the U.S. Defend Trade Secrets Act of 2016 (“DTSA”) provides that an individual shall not be held criminally or',
        x: 43.2,
        top: 185.12,
        size: 8,
      },
      {
        text: 'civilly liable under any federal or state trade secret law for the disclosure of a trade secret that is made (i) in confidence to a federal, state, or',
        x: 43.2,
        top: 196.62,
        size: 8,
      },
      {
        text: 'local government official, either directly or indirectly, or to an attorney; and (ii) solely for the purpose of reporting or investigating a suspected',
        x: 43.2,
        top: 208.12,
        size: 8,
      },
      {
        text: 'violation of law; or (iii) in a complaint or other document filed in a lawsuit or other proceeding, if such filing is made under seal. In addition,',
        x: 43.2,
        top: 219.62,
        size: 8,
      },
      {
        text: 'DTSA provides that an individual who files a lawsuit for retaliation by an employer for reporting a suspected violation of law may disclose the',
        x: 43.2,
        top: 231.12,
        size: 8,
      },
      {
        text: 'trade secret to the attorney of the individual and use the trade secret information in the court proceeding, if the individual (A) files any',
        x: 43.2,
        top: 242.62,
        size: 8,
      },
      {
        text: 'document containing the trade secret under seal; and (B) does not disclose the trade secret, except pursuant to court order.',
        x: 43.2,
        top: 254.12,
        size: 8,
      },
      {
        text: 'INVENTIONS RETAINED AND LICENSED',
        x: 43.2,
        top: 277.12,
        size: 8,
      },
      {
        text: 'I have attached hereto, a complete list describing with particularity all Inventions (as defined below) that, as of the Effective Date: (i) have',
        x: 43.2,
        top: 300.12,
        size: 8,
      },
      {
        text: 'been created by or on behalf of me, and/or (ii) are owned exclusively by me or jointly by me with others or in which I have an interest, and that',
        x: 43.2,
        top: 311.62,
        size: 8,
      },
      {
        text: 'relate in any way to any of Todd’s actual or proposed businesses, products, services, or research and development, and which are not',
        x: 43.2,
        top: 323.12,
        size: 8,
      },
      {
        text: 'assigned to Todd hereunder (collectively “Prior Inventions”); or, if no such list is attached, I represent and warrant that there are no such',
        x: 43.2,
        top: 334.62,
        size: 8,
      },
      {
        text: 'Inventions at the time of signing this Agreement, and to the extent such Inventions do exist and are not listed, I hereby irrevocably and forever',
        x: 43.2,
        top: 346.12,
        size: 8,
      },
      {
        text: 'waive any and all rights or claims of ownership to such Inventions. I understand that my listing of any Inventions does not constitute an',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'acknowledgement by Todd of the existence or extent of such Inventions, nor of my ownership of such Inventions. I further understand that I',
        x: 43.2,
        top: 369.12,
        size: 8,
      },
      {
        text: 'must receive the formal approval of Todd before commencing my Relationship with Todd.',
        x: 43.2,
        top: 380.62,
        size: 8,
      },
      {
        text: 'USE OR INCORPORATION OF INVENTIONS',
        x: 43.2,
        top: 403.62,
        size: 8,
      },
      {
        text: 'If in the course of the Relationship, I use or incorporate into any of Todd’s products, services, processes or machines any Invention not',
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: 'assigned to Todd pursuant to terms of this Agreement in which I have an interest, I will promptly so inform Todd in writing. Whether or not I',
        x: 43.2,
        top: 438.12,
        size: 8,
      },
      {
        text: 'give such notice, I hereby irrevocably grant to Todd a nonexclusive, fully paid-up, royalty-free, assumable, perpetual, worldwide license, with',
        x: 43.2,
        top: 449.62,
        size: 8,
      },
      {
        text: 'right to transfer and to sublicense, to practice and exploit such Invention and to make, have made, copy, modify, make derivative works of, use,',
        x: 43.2,
        top: 461.12,
        size: 8,
      },
      {
        text: 'sell, import, and otherwise distribute such Invention under all applicable intellectual property laws without restriction of any kind.',
        x: 43.2,
        top: 472.62,
        size: 8,
      },
      {
        text: 'INVENTIONS',
        x: 43.2,
        top: 495.62,
        size: 8,
      },
      {
        text: 'I understand that “Inventions” means discoveries, developments, concepts, designs, ideas, know how, modifications, improvements,',
        x: 43.2,
        top: 518.62,
        size: 8,
      },
      {
        text: 'derivative works, inventions, trade secrets and/or original works of authorship, whether or not patentable, copyrightable or otherwise legally',
        x: 43.2,
        top: 530.12,
        size: 8,
      },
      {
        text: 'protectable. I understand this includes, but is not limited to, any new product, machine, article of manufacture, biological material, method,',
        x: 43.2,
        top: 541.62,
        size: 8,
      },
      {
        text: 'procedure, process, technique, use, equipment, device, apparatus, system, compound, formulation, composition of matter, design or',
        x: 43.2,
        top: 553.12,
        size: 8,
      },
      {
        text: 'configuration of any kind, or any improvement thereon. I understand that “Todd Inventions” means any and all Inventions that I may solely or',
        x: 43.2,
        top: 564.62,
        size: 8,
      },
      {
        text: 'jointly author, discover, develop, conceive, or reduce to practice during the period of the Relationship or otherwise in connection with the',
        x: 43.2,
        top: 576.12,
        size: 8,
      },
      {
        text: 'Relationship, except as otherwise provided herein.',
        x: 43.2,
        top: 587.62,
        size: 8,
      },
      {
        text: 'ASSIGNMENT OF INVENTIONS',
        x: 43.2,
        top: 610.62,
        size: 8,
      },
      {
        text: 'I will promptly make full written disclosure to Todd, will hold in trust for the sole right and benefit of Todd, and hereby assign to Todd, or its',
        x: 43.2,
        top: 633.62,
        size: 8,
      },
      {
        text: 'designee, all of my right, title and interest throughout the world in and to any and all Todd Inventions and all patent, copyright, trademark,',
        x: 43.2,
        top: 645.12,
        size: 8,
      },
      {
        text: 'trade secret and other intellectual property rights and other proprietary rights therein. I hereby waive and irrevocably quitclaim to Todd or its',
        x: 43.2,
        top: 656.62,
        size: 8,
      },
      {
        text: 'designee any and all claims, of any nature whatsoever, that I now have or may hereafter have for infringement of any and all Todd Inventions. I',
        x: 43.2,
        top: 668.12,
        size: 8,
      },
      {
        text: 'further acknowledge that all Todd Inventions that are made by me (solely or jointly with others) within the scope of and during the period of',
        x: 43.2,
        top: 679.62,
        size: 8,
      },
      {
        text: 'the Relationship are “works made for hire” (to the greatest extent permitted by applicable law) and are compensated by my salary. Any',
        x: 43.2,
        top: 691.12,
        size: 8,
      },
      {
        text: 'assignment of Todd Inventions includes all rights of attribution, paternity, integrity, modification, disclosure and withdrawal, and any other',
        x: 43.2,
        top: 702.62,
        size: 8,
      },
      {
        text: 'rights throughout the world that may be known as or referred to as “moral rights,” “artist’s rights,” “droit moral,” or the like (collectively, “Moral',
        x: 43.2,
        top: 714.12,
        size: 8,
      },
      {
        text: 'Rights”). To the extent that Moral Rights cannot be assigned under applicable law, I hereby waive and agree not to enforce any and all Moral',
        x: 43.2,
        top: 725.62,
        size: 8,
      },
      {
        text: 'Rights, including, without limitation, any limitation on subsequent modification, to the extent permitted under applicable law. If I have any',
        x: 43.2,
        top: 737.12,
        size: 8,
      },
    ],
    rules: [
      {
        x0: 198.93,
        x1: 257.48,
        top: 340.84,
      },
      {
        x0: 544.28,
        x1: 565.98,
        top: 720.34,
      },
      {
        x0: 43.2,
        x1: 66.86,
        top: 731.84,
      },
    ],
  },
  {
    lines: [
      {
        text: 'rights to Todd Inventions, other than Moral Rights, that cannot be assigned to Todd, I hereby unconditionally and irrevocably grant to Todd',
        x: 43.2,
        top: 47.12,
        size: 8,
      },
      {
        text: 'during the term of such rights, an exclusive, irrevocable, perpetual, worldwide, fully paid and royalty-free license, with rights to sublicense',
        x: 43.2,
        top: 58.62,
        size: 8,
      },
      {
        text: 'through multiple levels of sublicensees, to reproduce, distribute, display, perform, prepare derivative works of and otherwise modify, make,',
        x: 43.2,
        top: 70.12,
        size: 8,
      },
      {
        text: 'have made, sell, offer to sell, import, practice methods, processes and procedures and otherwise use and exploit, such Todd Inventions.',
        x: 43.2,
        top: 81.62,
        size: 8,
      },
      {
        text: 'MAINTENANCE OF RECORDS',
        x: 43.2,
        top: 104.62,
        size: 8,
      },
      {
        text: 'I shall keep and maintain adequate and current written records of all Todd Inventions made or conceived by me (solely or jointly with others)',
        x: 43.2,
        top: 127.62,
        size: 8,
      },
      {
        text: 'during the term of the Relationship. The records may be in the form of notes, sketches, drawings, flow charts, electronic data or recordings,',
        x: 43.2,
        top: 139.12,
        size: 8,
      },
      {
        text: 'laboratory notebooks, or any other format. The records will be available to and remain the sole property of Todd at all times. I shall not remove',
        x: 43.2,
        top: 150.62,
        size: 8,
      },
      {
        text: 'such records from the Todd’s place of business or systems except as expressly permitted by Todd policy which may, from time to time, be',
        x: 43.2,
        top: 162.12,
        size: 8,
      },
      {
        text: 'revised at the sole election of Todd for the purpose of furthering Todd’s business. I shall deliver all such records (including any copies thereof)',
        x: 43.2,
        top: 173.62,
        size: 8,
      },
      {
        text: 'to Todd at the time of termination of the Relationship as provided for herein.',
        x: 43.2,
        top: 185.12,
        size: 8,
      },
      {
        text: 'INTELLECTUAL PROPERTY RIGHTS',
        x: 43.2,
        top: 208.12,
        size: 8,
      },
      {
        text: 'I shall assist Todd, or its designee, at its expense, in every proper way in securing Todd’s, or its designee’s, rights in Todd’s Inventions and any',
        x: 43.2,
        top: 231.12,
        size: 8,
      },
      {
        text: 'copyrights, patents, trademarks, mask work rights, Moral Rights, or other intellectual property rights relating thereto in any and all countries,',
        x: 43.2,
        top: 242.62,
        size: 8,
      },
      {
        text: 'including the disclosure to Todd or its designee of all pertinent information and data with respect thereto, the execution of all applications,',
        x: 43.2,
        top: 254.12,
        size: 8,
      },
      {
        text: 'specifications, oaths, assignments, recordations, and all other instruments which Todd or its designee shall deem necessary in order to apply',
        x: 43.2,
        top: 265.62,
        size: 8,
      },
      {
        text: 'for, obtain, maintain and transfer such rights, or if not transferable, waive and shall never assert such rights, and in order to assign and convey',
        x: 43.2,
        top: 277.12,
        size: 8,
      },
      {
        text: 'to Todd or its designee, and any successors, assigns and nominees the sole and exclusive right, title and interest in and to such Todd',
        x: 43.2,
        top: 288.62,
        size: 8,
      },
      {
        text: 'Inventions, and any copyrights, patents, mask work rights or other intellectual property rights relating thereto. My obligation to execute or',
        x: 43.2,
        top: 300.12,
        size: 8,
      },
      {
        text: 'cause to be executed, when it is in my power to do so, any such instrument or papers shall continue during and at all times after the end of the',
        x: 43.2,
        top: 311.62,
        size: 8,
      },
      {
        text: 'Relationship and until the expiration of the last such intellectual property right to expire in any country of the world. I hereby irrevocably',
        x: 43.2,
        top: 323.12,
        size: 8,
      },
      {
        text: 'designate and appoint Todd and its duly authorized officers and agents as my agent and attorney-in-fact, to act for and in my behalf and stead',
        x: 43.2,
        top: 334.62,
        size: 8,
      },
      {
        text: 'to execute and file any such instruments and papers and to do all other lawfully permitted acts to further the application for, prosecution,',
        x: 43.2,
        top: 346.12,
        size: 8,
      },
      {
        text: 'issuance, maintenance or transfer of letters patent, copyright, mask work and other registrations related to such Todd Inventions. This power',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'of attorney is coupled with an interest and shall not be affected by my subsequent incapacity.',
        x: 43.2,
        top: 369.12,
        size: 8,
      },
      {
        text: 'EXCEPTION TO ASSIGNMENTS',
        x: 43.2,
        top: 392.12,
        size: 8,
      },
      {
        text: 'Subject to the requirements of applicable state law, if any, I understand that Todd Inventions will not include, and the provisions of this',
        x: 43.2,
        top: 415.12,
        size: 8,
      },
      {
        text: 'Agreement requiring assignment of inventions to Todd do not apply to, any invention which qualifies fully for exclusion under the provisions of',
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: 'applicable state law, if any. In order to assist in the determination of which inventions qualify for such exclusion, I will advise Todd promptly in',
        x: 43.2,
        top: 438.12,
        size: 8,
      },
      {
        text: 'writing, during and for a period of twelve (12) months immediately following the termination of the Relationship, of all Inventions solely or',
        x: 43.2,
        top: 449.62,
        size: 8,
      },
      {
        text: 'jointly conceived or developed or reduced to practice by me during the period of the Relationship.',
        x: 43.2,
        top: 461.12,
        size: 8,
      },
      {
        text: 'COMPANY PROPERTY; RETURNING COMPANY MATERIAL',
        x: 43.2,
        top: 484.12,
        size: 8,
      },
      {
        text: 'I acknowledge that I have no expectation of privacy with respect to Todd’s telecommunications, networking or information processing',
        x: 43.2,
        top: 507.12,
        size: 8,
      },
      {
        text: 'systems (including, without limitation, files, e-mail messages, and voice messages) and that my activity and any files or messages on or using',
        x: 43.2,
        top: 518.62,
        size: 8,
      },
      {
        text: "any of those systems may be monitored or reviewed at any time without notice. I further acknowledge that any property situated on Todd's",
        x: 43.2,
        top: 530.12,
        size: 8,
      },
      {
        text: 'premises or systems and owned by Todd, including disks and other storage media, filing cabinets or other work areas, is subject to inspection',
        x: 43.2,
        top: 541.62,
        size: 8,
      },
      {
        text: 'by Todd personnel at any time with or without notice. At the time of termination of the Relationship, I will deliver to Todd (and will not keep in',
        x: 43.2,
        top: 553.12,
        size: 8,
      },
      {
        text: 'my possession, recreate or deliver to anyone else) any and all devices, records, data, notes, reports, proposals, lists, correspondence,',
        x: 43.2,
        top: 564.62,
        size: 8,
      },
      {
        text: 'specifications, drawings, blueprints, sketches, laboratory notebooks, materials, flow charts, equipment, other documents or property, or',
        x: 43.2,
        top: 576.12,
        size: 8,
      },
      {
        text: 'reproductions of any of the aforementioned items developed by me pursuant to the Relationship or otherwise belonging to Todd, its',
        x: 43.2,
        top: 587.62,
        size: 8,
      },
      {
        text: 'successors or assigns.',
        x: 43.2,
        top: 599.12,
        size: 8,
      },
      {
        text: 'TERMINATION CERTIFICATION',
        x: 43.2,
        top: 622.12,
        size: 8,
      },
      {
        text: 'In the event of the termination of the Relationship, I shall sign and deliver the “Termination Certification” attached hereto; however, my failure',
        x: 43.2,
        top: 645.12,
        size: 8,
      },
      {
        text: 'to sign and deliver the Termination Certification shall in no way diminish my continuing obligations under this Agreement.',
        x: 43.2,
        top: 656.62,
        size: 8,
      },
      {
        text: 'NOTICE TO THIRD PARTIES',
        x: 43.2,
        top: 679.62,
        size: 8,
      },
      {
        text: 'During the periods of time during which I am restricted in taking certain actions by the terms of Section 8 of this Agreement (the “Restriction',
        x: 43.2,
        top: 702.62,
        size: 8,
      },
      {
        text: 'Period”), I shall inform any entity or person with whom I may seek to enter into a business relationship (whether as an owner, employee,',
        x: 43.2,
        top: 714.12,
        size: 8,
      },
      {
        text: 'independent contractor or otherwise) of my contractual obligations under this Agreement. I acknowledge that the Company may, with or',
        x: 43.2,
        top: 725.62,
        size: 8,
      },
      {
        text: 'without prior notice to me and whether during or after the term of the Relationship, notify third parties of my agreements and obligations',
        x: 43.2,
        top: 737.12,
        size: 8,
      },
    ],
    rules: [
      {
        x0: 332.52,
        x1: 424.41,
        top: 651.34,
      },
      {
        x0: 522.85,
        x1: 563.37,
        top: 708.84,
      },
      {
        x0: 43.2,
        x1: 67.46,
        top: 720.34,
      },
    ],
  },
  {
    lines: [
      {
        text: 'under this Agreement. Upon written request by the Company, I will respond to the Company in writing regarding the status of my employment',
        x: 43.2,
        top: 47.12,
        size: 8,
      },
      {
        text: 'or proposed employment with any party during the Restriction Period.',
        x: 43.2,
        top: 58.62,
        size: 8,
      },
      {
        text: 'SOLICITATION OF EMPLOYEES, CONSULTANTS AND OTHER PARTIES',
        x: 43.2,
        top: 81.62,
        size: 8,
      },
      {
        text: 'As described above, I acknowledge that Todd’s Confidential Information includes information relating to Todd’s employees, consultants,',
        x: 43.2,
        top: 104.62,
        size: 8,
      },
      {
        text: 'customers and others, and I will not use or disclose such Confidential Information except as authorized by Todd in advance in writing. I further',
        x: 43.2,
        top: 116.12,
        size: 8,
      },
      {
        text: 'agree as follows: (i) During the term of the Relationship, and for a period of twelve (12) months immediately following the termination of the',
        x: 43.2,
        top: 127.62,
        size: 8,
      },
      {
        text: 'Relationship for any reason, whether with or without cause, I shall not, directly or indirectly, solicit any of Todd’s employees or consultants to',
        x: 43.2,
        top: 139.12,
        size: 8,
      },
      {
        text: 'terminate their relationship with Todd, or attempt to solicit employees or consultants of Todd, either for myself or for any other person or',
        x: 43.2,
        top: 150.62,
        size: 8,
      },
      {
        text: 'entity; and (ii) During the term of the Relationship, I will not influence any of Todd’s clients, licensors, or licensees from purchasing Todd',
        x: 43.2,
        top: 162.12,
        size: 8,
      },
      {
        text: 'products or services or solicit or influence or attempt to influence any client, licensor, licensee or other person either directly or indirectly, to',
        x: 43.2,
        top: 173.62,
        size: 8,
      },
      {
        text: 'direct any purchase of products and/or services to any person, firm, corporation, institution or other entity in competition with the business of',
        x: 43.2,
        top: 185.12,
        size: 8,
      },
      {
        text: 'Todd.',
        x: 43.2,
        top: 196.62,
        size: 8,
      },
      {
        text: 'AT-WILL RELATIONSHIP',
        x: 43.2,
        top: 219.62,
        size: 8,
      },
      {
        text: 'I understand and acknowledge that, except as may be otherwise explicitly provided in a separate written agreement between Todd and me,',
        x: 43.2,
        top: 242.62,
        size: 8,
      },
      {
        text: 'my Relationship with Todd is and shall continue to be at-will, as defined under applicable law, meaning that either I or Todd may terminate the',
        x: 43.2,
        top: 254.12,
        size: 8,
      },
      {
        text: 'Relationship at any time for any reason or no reason, without further obligation or liability, other than those provisions of this Agreement that',
        x: 43.2,
        top: 265.62,
        size: 8,
      },
      {
        text: 'explicitly continue in effect after the termination of the Relationship.',
        x: 43.2,
        top: 277.12,
        size: 8,
      },
      {
        text: 'FACILITATION OF AGREEMENT',
        x: 43.2,
        top: 300.12,
        size: 8,
      },
      {
        text: 'I shall execute promptly, both during and after the end of the Relationship, any proper oath, and to verify any proper document, required to',
        x: 43.2,
        top: 323.12,
        size: 8,
      },
      {
        text: 'carry out the terms of this Agreement, upon Todd’s written request to do so.',
        x: 43.2,
        top: 334.62,
        size: 8,
      },
      {
        text: 'NO CONFLICTS',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'I represent and warrant that my performance of all the terms of this Agreement does not and will not breach any agreement I have entered',
        x: 43.2,
        top: 380.62,
        size: 8,
      },
      {
        text: 'into, or will enter into, with any third party, including without limitation any agreement to keep in confidence proprietary information or',
        x: 43.2,
        top: 392.12,
        size: 8,
      },
      {
        text: 'materials acquired by me in confidence or in trust prior to or during the Relationship. I will not disclose to Todd or use any inventions,',
        x: 43.2,
        top: 403.62,
        size: 8,
      },
      {
        text: 'confidential or non-public proprietary information or material belonging to any previous client, employer or any other party. I will not induce',
        x: 43.2,
        top: 415.12,
        size: 8,
      },
      {
        text: 'Todd to use any inventions, confidential or non-public proprietary information, or material belonging to any previous client, employer or any',
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: 'other party. I represent and warrant that I have listed on the Signature Page all agreements (e.g., non-competition agreements, non-',
        x: 43.2,
        top: 438.12,
        size: 8,
      },
      {
        text: 'solicitation of client agreements, non-solicitation of employees agreements, confidentiality agreements, inventions agreements, etc.), if any,',
        x: 43.2,
        top: 449.62,
        size: 8,
      },
      {
        text: 'with a current or former client, employer, or any other person or entity, that may restrict my ability to accept employment with Todd or my',
        x: 43.2,
        top: 461.12,
        size: 8,
      },
      {
        text: 'ability to recruit or engage clients or service providers on behalf of Todd, or otherwise relate to or restrict my ability to perform my duties for',
        x: 43.2,
        top: 472.62,
        size: 8,
      },
      {
        text: 'Todd or any obligation I may have to Todd. I shall not enter into any written or oral agreement that conflicts with the provisions of this',
        x: 43.2,
        top: 484.12,
        size: 8,
      },
      {
        text: 'Agreement.',
        x: 43.2,
        top: 495.62,
        size: 8,
      },
      {
        text: 'NON-COMPETE',
        x: 43.2,
        top: 518.62,
        size: 8,
      },
      {
        text: 'This Agreement is not a non-compete agreement and does not restrict you from seeking or accepting employment with a competitor. Your',
        x: 43.2,
        top: 541.62,
        size: 8,
      },
      {
        text: 'ability to work for a competitor is subject to your strict and ongoing adherence to this Agreement.',
        x: 43.2,
        top: 553.12,
        size: 8,
      },
      {
        text: 'VOLUNTARY EXECUTION',
        x: 43.2,
        top: 576.12,
        size: 8,
      },
      {
        text: 'I certify and acknowledge that I have carefully read all of the provisions of this Agreement, that I understand and have voluntarily accepted',
        x: 43.2,
        top: 599.12,
        size: 8,
      },
      {
        text: 'such provisions, and that I will fully and faithfully comply with such provisions.',
        x: 43.2,
        top: 610.62,
        size: 8,
      },
      {
        text: 'ELECTRONIC DELIVERY',
        x: 43.2,
        top: 633.62,
        size: 8,
      },
      {
        text: 'Nothing herein is intended to imply a right to participate in any of Todd’s equity incentive plans, however, if I do participate in such plan(s),',
        x: 43.2,
        top: 656.62,
        size: 8,
      },
      {
        text: 'Todd may, in its sole discretion, decide to deliver any documents related to my participation in Todd’s equity inventive plan(s) by electronic',
        x: 43.2,
        top: 668.12,
        size: 8,
      },
      {
        text: 'means or to request my consent to participate in such plan(s) by electronic means. I hereby consent to receive such documents by electronic',
        x: 43.2,
        top: 679.62,
        size: 8,
      },
      {
        text: 'delivery and agree, if applicable, to participate in such plan(s) through an online or electronic system established and maintained by Todd or a',
        x: 43.2,
        top: 691.12,
        size: 8,
      },
      {
        text: 'third party designated by Todd.',
        x: 43.2,
        top: 702.62,
        size: 8,
      },
      {
        text: 'GOVERNING LAW',
        x: 43.2,
        top: 725.62,
        size: 8,
      },
    ],
    rules: [],
  },
  {
    lines: [
      {
        text: 'The validity, interpretation, construction and performance of this Agreement, and all acts and transactions pursuant hereto and the rights and',
        x: 43.2,
        top: 47.12,
        size: 8,
      },
      {
        text: 'obligations of the parties hereto shall be governed, construed and interpreted in accordance with the laws of the state of Delaware without',
        x: 43.2,
        top: 58.62,
        size: 8,
      },
      {
        text: 'giving effect to principles of conflicts of law.',
        x: 43.2,
        top: 70.12,
        size: 8,
      },
      {
        text: 'ENTIRE AGREEMENT',
        x: 43.2,
        top: 93.12,
        size: 8,
      },
      {
        text: 'This Agreement sets forth the entire agreement and understanding between Todd and me relating to its subject matter and merges all prior',
        x: 43.2,
        top: 116.12,
        size: 8,
      },
      {
        text: 'discussions between us. No amendment to this Agreement will be effective unless in writing signed by both parties to this Agreement. Todd',
        x: 43.2,
        top: 127.62,
        size: 8,
      },
      {
        text: 'shall not be deemed hereby to have waived any rights or remedies it may have in law or equity, nor to have given any authorizations or waived',
        x: 43.2,
        top: 139.12,
        size: 8,
      },
      {
        text: 'any of its rights under this Agreement, unless, and only to the extent, it does so by a specific writing signed by a duly authorized officer of',
        x: 43.2,
        top: 150.62,
        size: 8,
      },
      {
        text: 'Todd, it being understood that, even if I am an officer of Todd, I will not have authority to give any such authorizations or waivers for Todd',
        x: 43.2,
        top: 162.12,
        size: 8,
      },
      {
        text: 'under this Agreement without specific approval by the Board of Directors. Any subsequent change or changes in my duties, obligations, rights',
        x: 43.2,
        top: 173.62,
        size: 8,
      },
      {
        text: 'or compensation will not affect the validity or scope of this Agreement.',
        x: 43.2,
        top: 185.12,
        size: 8,
      },
      {
        text: 'SUCCESSORS AND ASSIGNS',
        x: 43.2,
        top: 208.12,
        size: 8,
      },
      {
        text: 'This Agreement will be binding upon my heirs, executors, administrators and other legal representatives, and my successors and assigns, and',
        x: 43.2,
        top: 231.12,
        size: 8,
      },
      {
        text: 'will be for the benefit of Todd, its successors, and its assigns.',
        x: 43.2,
        top: 242.62,
        size: 8,
      },
      {
        text: 'NOTICES',
        x: 43.2,
        top: 265.62,
        size: 8,
      },
      {
        text: 'Any notice, demand or request required or permitted to be given under this Agreement shall be in writing and shall be deemed sufficient',
        x: 43.2,
        top: 288.62,
        size: 8,
      },
      {
        text: 'when delivered personally or by overnight courier or sent by email, or 48 hours after being deposited in the U.S. mail as certified or registered',
        x: 43.2,
        top: 300.12,
        size: 8,
      },
      {
        text: 'mail with postage prepaid, addressed to the party to be notified at such party’s address as set forth on the signature page, as subsequently',
        x: 43.2,
        top: 311.62,
        size: 8,
      },
      {
        text: 'modified by written notice, or if no address is specified on the signature page, at the most recent address set forth in the Company’s books',
        x: 43.2,
        top: 323.12,
        size: 8,
      },
      {
        text: 'and records.',
        x: 43.2,
        top: 334.62,
        size: 8,
      },
      {
        text: 'SEVERABILITY',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'If one or more of the provisions in this Agreement are deemed void or unenforceable to any extent in any context, such provisions shall',
        x: 43.2,
        top: 380.62,
        size: 8,
      },
      {
        text: 'nevertheless be enforced to the fullest extent allowed by law in that and other contexts, and the validity and force of the remainder of this',
        x: 43.2,
        top: 392.12,
        size: 8,
      },
      {
        text: 'Agreement shall not be affected. Todd and I have attempted to limit my right to use, maintain and disclose Todd’s Confidential Information,',
        x: 43.2,
        top: 403.62,
        size: 8,
      },
      {
        text: 'and to limit my right to solicit employees and customers only to the extent necessary to protect Todd from unfair competition. Should a court',
        x: 43.2,
        top: 415.12,
        size: 8,
      },
      {
        text: 'of competent jurisdiction determine that the scope of the covenants contained exceeds the maximum restrictiveness such court deems',
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: 'reasonable and enforceable, the parties intend that the court should reform, modify and enforce the provision to such narrower scope as it',
        x: 43.2,
        top: 438.12,
        size: 8,
      },
      {
        text: 'determines to be reasonable and enforceable under the circumstances existing at that time.',
        x: 43.2,
        top: 449.62,
        size: 8,
      },
      {
        text: 'REMEDIES',
        x: 43.2,
        top: 472.62,
        size: 8,
      },
      {
        text: 'I acknowledge that violation of this Agreement by me may cause Todd irreparable harm, and therefore I agree that Todd will be entitled to',
        x: 43.2,
        top: 495.62,
        size: 8,
      },
      {
        text: 'seek extraordinary relief in court, including, but not limited to, temporary restraining orders, preliminary injunctions and permanent',
        x: 43.2,
        top: 507.12,
        size: 8,
      },
      {
        text: 'injunctions without the necessity of posting a bond or other security (or, where such a bond or security is required, that a $1,000 bond will be',
        x: 43.2,
        top: 518.62,
        size: 8,
      },
      {
        text: 'adequate), in addition to and without prejudice to any other rights or remedies that Todd may have for a breach of this Agreement.',
        x: 43.2,
        top: 530.12,
        size: 8,
      },
      {
        text: 'ADVICE OF COUNSEL',
        x: 43.2,
        top: 553.12,
        size: 8,
      },
      {
        text: 'I ACKNOWLEDGE THAT, IN EXECUTING THIS AGREEMENT, I HAVE HAD THE OPPORTUNITY TO SEEK THE ADVICE OF INDEPENDENT',
        x: 43.2,
        top: 576.12,
        size: 8,
      },
      {
        text: 'LEGAL COUNSEL, AND I HAVE READ AND UNDERSTOOD ALL OF THE TERMS AND PROVISIONS OF THIS AGREEMENT. THIS',
        x: 43.2,
        top: 587.62,
        size: 8,
      },
      {
        text: 'AGREEMENT SHALL NOT BE CONSTRUED AGAINST ANY PARTY BY REASON OF THE DRAFTING OR PREPARATION HEREOF.',
        x: 43.2,
        top: 599.12,
        size: 8,
      },
      {
        text: 'COUNTERPARTS',
        x: 43.2,
        top: 622.12,
        size: 8,
      },
      {
        text: 'This Agreement may be executed in any number of counterparts, each of which when so executed and delivered shall be deemed an original,',
        x: 43.2,
        top: 645.12,
        size: 8,
      },
      {
        text: 'and all of which together shall constitute one and the same agreement. Execution of a facsimile or scanned copy will have the same force and',
        x: 43.2,
        top: 656.62,
        size: 8,
      },
      {
        text: 'effect as execution of an original, and a facsimile or scanned signature will be deemed an original and valid signature.',
        x: 43.2,
        top: 668.12,
        size: 8,
      },
      {
        text: 'MISCELLANEOUS',
        x: 43.2,
        top: 691.12,
        size: 8,
      },
      {
        text: 'Headings and captions throughout this Agreement are for convenience only and should not be considered part of this Agreement. The word',
        x: 43.2,
        top: 714.12,
        size: 8,
      },
      {
        text: '“including” means “including without limitation”.',
        x: 43.2,
        top: 725.62,
        size: 8,
      },
    ],
    rules: [],
  },
  {
    lines: [
      {
        text: 'Important Information for CA, WA, IL, KA and MN Residents:',
        x: 43.2,
        top: 47.12,
        size: 8,
      },
      {
        text: 'CALIFORNIA RESIDENTS:',
        x: 43.2,
        top: 70.12,
        size: 8,
      },
      {
        text: '(a) Any provision in an employment agreement which provides that an employee shall assign, or offer to assign, any of his or her rights',
        x: 43.2,
        top: 93.12,
        size: 8,
      },
      {
        text: 'in an invention to his or her employer shall not apply to an invention that the employee developed entirely on his or her own time without',
        x: 43.2,
        top: 104.62,
        size: 8,
      },
      {
        text: 'using the employer’s equipment, supplies, facilities, or trade secret information except for those inventions that either:',
        x: 43.2,
        top: 116.12,
        size: 8,
      },
      {
        text: '(1) Relate at the time of conception or reduction to practice of the invention to the employer’s business, or actual or',
        x: 79.2,
        top: 127.62,
        size: 8,
      },
      {
        text: 'demonstrably anticipated research or development of the employer; or',
        x: 43.2,
        top: 139.12,
        size: 8,
      },
      {
        text: '(2) Result from any work performed by the employee for the employer.',
        x: 79.2,
        top: 150.62,
        size: 8,
      },
      {
        text: '(b) To the extent a provision in an employment agreement purports to require an employee to assign an invention otherwise excluded',
        x: 43.2,
        top: 173.62,
        size: 8,
      },
      {
        text: 'from being required to be assigned under subdivision (a), the provision is against the public policy of this state and is unenforceable.',
        x: 43.2,
        top: 185.12,
        size: 8,
      },
      {
        text: 'WASHINGTON RESIDENTS:',
        x: 43.2,
        top: 208.12,
        size: 8,
      },
      {
        text: '(1) A provision in an employment agreement which provides that an employee shall assign or offer to assign any of the employee’s',
        x: 43.2,
        top: 231.12,
        size: 8,
      },
      {
        text: 'rights in an invention to the employer does not apply to an invention for which no equipment, supplies, facilities, or trade secret information of',
        x: 43.2,
        top: 242.62,
        size: 8,
      },
      {
        text: 'the employer was used and which was developed entirely on the employee’s own time, unless (a) the invention relates (i) directly to the',
        x: 43.2,
        top: 254.12,
        size: 8,
      },
      {
        text: "business of the employer, or (ii) to the employer's actual or demonstrably anticipated research or development, or (b) the invention results",
        x: 43.2,
        top: 265.62,
        size: 8,
      },
      {
        text: 'from any work performed by the employee for the employer. Any provision which purports to apply to such an invention is to that extent',
        x: 43.2,
        top: 277.12,
        size: 8,
      },
      {
        text: 'against the public policy of this state and is to that extent void and unenforceable.',
        x: 43.2,
        top: 288.62,
        size: 8,
      },
      {
        text: '(2) An employer shall not require a provision made void and unenforceable by subsection (1) of this section as a condition of',
        x: 43.2,
        top: 311.62,
        size: 8,
      },
      {
        text: 'employment or continuing employment.',
        x: 43.2,
        top: 323.12,
        size: 8,
      },
      {
        text: '(3) If an employment agreement entered into after September 1, 1979, contains a provision requiring the employee to assign any of the',
        x: 43.2,
        top: 346.12,
        size: 8,
      },
      {
        text: 'employee’s rights in any invention to the employer, the employer must also, at the time the agreement is made, provide a written notification to',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'the employee that the agreement does not apply to an invention for which no equipment, supplies, facility, or trade secret information of the',
        x: 43.2,
        top: 369.12,
        size: 8,
      },
      {
        text: 'employer was used and which was developed entirely on the employee’s own time, unless (a) the invention relates (i) directly to the business',
        x: 43.2,
        top: 380.62,
        size: 8,
      },
      {
        text: "of the employer, or (ii) to the employer's actual or demonstrably anticipated research or development, or (b) the invention results from any",
        x: 43.2,
        top: 392.12,
        size: 8,
      },
      {
        text: 'work performed by the employee for the employer.',
        x: 43.2,
        top: 403.62,
        size: 8,
      },
      {
        text: 'ILLINOIS RESIDENTS:',
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: "(1) A provision in an employment agreement which provides that an employee shall assign or offer to assign any of the employee's",
        x: 43.2,
        top: 449.62,
        size: 8,
      },
      {
        text: 'rights in an invention to the employer does not apply to an invention for which no equipment, supplies, facilities, or trade secret information of',
        x: 43.2,
        top: 461.12,
        size: 8,
      },
      {
        text: "the employer was used and which was developed entirely on the employee's own time, unless (a) the invention relates (i) to the business of",
        x: 43.2,
        top: 472.62,
        size: 8,
      },
      {
        text: "the employer, or (ii) to the employer's actual or demonstrably anticipated research or development, or (b) the invention results from any work",
        x: 43.2,
        top: 484.12,
        size: 8,
      },
      {
        text: 'performed by the employee for the employer. Any provision which purports to apply to such an invention is to that extent against the public',
        x: 43.2,
        top: 495.62,
        size: 8,
      },
      {
        text: 'policy of this State and is to that extent void and unenforceable. The employee shall bear the burden of proof in establishing that his invention',
        x: 43.2,
        top: 507.12,
        size: 8,
      },
      {
        text: 'qualifies under this subsection.',
        x: 43.2,
        top: 518.62,
        size: 8,
      },
      {
        text: '(2) An employer shall not require a provision made void and unenforceable by subsection (1) of this Section as a condition of',
        x: 43.2,
        top: 541.62,
        size: 8,
      },
      {
        text: 'employment or continuing employment. This Act shall not preempt existing common law applicable to any shop rights of employers with',
        x: 43.2,
        top: 553.12,
        size: 8,
      },
      {
        text: 'respect to employees who have not signed an employment agreement.',
        x: 43.2,
        top: 564.62,
        size: 8,
      },
      {
        text: '(3) If an employment agreement entered into after January 1, 1984, contains a provision requiring the employee to assign any of the',
        x: 43.2,
        top: 587.62,
        size: 8,
      },
      {
        text: "employee's rights in any invention to the employer, the employer must also, at the time the agreement is made, provide a written notification to",
        x: 43.2,
        top: 599.12,
        size: 8,
      },
      {
        text: 'the employee that the agreement does not apply to an invention for which no equipment, supplies, facility, or trade secret information of the',
        x: 43.2,
        top: 610.62,
        size: 8,
      },
      {
        text: "employer was used and which was developed entirely on the employee's own time, unless (a) the invention relates (i) to the business of the",
        x: 43.2,
        top: 622.12,
        size: 8,
      },
      {
        text: "employer, or (ii) to the employer's actual or demonstrably anticipated research or development, or (b) the invention results from any work",
        x: 43.2,
        top: 633.62,
        size: 8,
      },
      {
        text: 'performed by the employee for the employer.',
        x: 43.2,
        top: 645.12,
        size: 8,
      },
      {
        text: 'KANSAS RESIDENTS:',
        x: 43.2,
        top: 668.12,
        size: 8,
      },
      {
        text: "(a) Any provision in an employment agreement which provides that an employee shall assign or offer to assign any of the employee's",
        x: 43.2,
        top: 691.12,
        size: 8,
      },
      {
        text: 'rights in an invention to the employer shall not apply to an invention for which no equipment, supplies, facilities or trade secret information of',
        x: 43.2,
        top: 702.62,
        size: 8,
      },
      {
        text: "the employer was used and which was developed entirely on the employee's own time, unless:",
        x: 43.2,
        top: 714.12,
        size: 8,
      },
      {
        text: "(1) The invention relates to the business of the employer or to the employer's actual or demonstrably anticipated research or",
        x: 79.2,
        top: 725.62,
        size: 8,
      },
      {
        text: 'development; or',
        x: 43.2,
        top: 737.12,
        size: 8,
      },
    ],
    rules: [
      {
        x0: 43.2,
        x1: 266.14,
        top: 53.34,
        fitToText: true,
      },
    ],
  },
  {
    lines: [
      {
        text: '(2) the invention results from any work performed by the employee for the employer.',
        x: 79.2,
        top: 47.12,
        size: 8,
      },
      {
        text: '(b) Any provision in an employment agreement which purports to apply to an invention which it is prohibited from applying to under',
        x: 43.2,
        top: 70.12,
        size: 8,
      },
      {
        text: 'subsection (a), is to that extent against the public policy of this state and is to that extent void and unenforceable. No employer shall require a',
        x: 43.2,
        top: 81.62,
        size: 8,
      },
      {
        text: 'provision made void and unenforceable by this section as a condition of employment or continuing employment.',
        x: 43.2,
        top: 93.12,
        size: 8,
      },
      {
        text: "(c) If an employment agreement contains a provision requiring the employee to assign any of the employee's rights in any invention to",
        x: 43.2,
        top: 116.12,
        size: 8,
      },
      {
        text: 'the employer, the employer shall provide, at the time the agreement is made, a written notification to the employee that the agreement does',
        x: 43.2,
        top: 127.62,
        size: 8,
      },
      {
        text: 'not apply to an invention for which no equipment, supplies, facility or trade secret information of the employer was used and which was',
        x: 43.2,
        top: 139.12,
        size: 8,
      },
      {
        text: "developed entirely on the employee's own time, unless:",
        x: 43.2,
        top: 150.62,
        size: 8,
      },
      {
        text: "(1) The invention relates directly to the business of the employer or to the employer's actual or demonstrably anticipated",
        x: 79.2,
        top: 162.12,
        size: 8,
      },
      {
        text: 'research or development; or',
        x: 43.2,
        top: 173.62,
        size: 8,
      },
      {
        text: '(2) The invention results from any work performed by the employee for the employer.',
        x: 79.2,
        top: 185.12,
        size: 8,
      },
      {
        text: '(d) Even though the employee meets the burden of proving the conditions specified in this section, the employee shall disclose, at the',
        x: 43.2,
        top: 208.12,
        size: 8,
      },
      {
        text: 'time of employment or thereafter, all inventions being developed by the employee, for the purpose of determining employer and employee',
        x: 43.2,
        top: 219.62,
        size: 8,
      },
      {
        text: 'rights in an invention.',
        x: 43.2,
        top: 231.12,
        size: 8,
      },
      {
        text: 'MINNISOTA RESIDENTS:',
        x: 43.2,
        top: 254.12,
        size: 8,
      },
      {
        text: 'Subdivision 1. Inventions not related to employment. Any provision in an employment agreement which provides that an employee shall',
        x: 43.2,
        top: 277.12,
        size: 8,
      },
      {
        text: "assign or offer to assign any of the employee's rights in an invention to the employer shall not apply to an invention for which no equipment,",
        x: 43.2,
        top: 288.62,
        size: 8,
      },
      {
        text: "supplies, facility or trade secret information of the employer was used and which was developed entirely on the employee's own time, and (1)",
        x: 43.2,
        top: 300.12,
        size: 8,
      },
      {
        text: "which does not relate (a) directly to the business of the employer or (b) to the employer's actual or demonstrably anticipated research or",
        x: 43.2,
        top: 311.62,
        size: 8,
      },
      {
        text: 'development, or (2) which does not result from any work performed by the employee for the employer. Any provision which purports to apply',
        x: 43.2,
        top: 323.12,
        size: 8,
      },
      {
        text: 'to such an invention is to that extent against the public policy of this state and is to that extent void and unenforceable.',
        x: 43.2,
        top: 334.62,
        size: 8,
      },
      {
        text: 'Subd. 2. Effect of subdivision 1. No employer shall require a provision made void and unenforceable by subdivision 1 as a condition of',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'employment or continuing employment.',
        x: 43.2,
        top: 369.12,
        size: 8,
      },
      {
        text: 'Subd. 3. Notice to employee. If an employment agreement entered into after August 1, 1977 contains a provision requiring the employee to',
        x: 43.2,
        top: 392.12,
        size: 8,
      },
      {
        text: "assign or offer to assign any of the employee's rights in any invention to an employer, the employer must also, at the time the agreement is",
        x: 43.2,
        top: 403.62,
        size: 8,
      },
      {
        text: 'made, provide a written notification to the employee that the agreement does not apply to an invention for which no equipment, supplies,',
        x: 43.2,
        top: 415.12,
        size: 8,
      },
      {
        text: "facility or trade secret information of the employer was used and which was developed entirely on the employee's own time, and (1) which",
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: "does not relate (a) directly to the business of the employer or (b) to the employer's actual or demonstrably anticipated research or",
        x: 43.2,
        top: 438.12,
        size: 8,
      },
      {
        text: 'development, or (2) which does not result from any work performed by the employee for the employer.',
        x: 43.2,
        top: 449.62,
        size: 8,
      },
    ],
    rules: [],
  },
  {
    lines: [
      {
        text: 'List of Prior Inventions and Original Works of Authorship Excluded Under This Agreement',
        x: 43.2,
        top: 47.12,
        size: 8,
      },
      {
        text: 'The following is a list of all Inventions that, as of the Effective Date: (a) have been created by me or on my behalf, and/or (b) are owned',
        x: 43.2,
        top: 70.12,
        size: 8,
      },
      {
        text: 'exclusively by me or jointly by me with others or in which I have an interest, and that relate in any way to any of Todd’s actual or proposed',
        x: 43.2,
        top: 81.62,
        size: 8,
      },
      {
        text: 'businesses, products, services, or research and development, and which are not assigned to Todd hereunder:',
        x: 43.2,
        top: 93.12,
        size: 8,
      },
      {
        text: '1:',
        x: 43.2,
        top: 116.12,
        size: 8,
      },
      {
        text: '2:',
        x: 43.2,
        top: 139.12,
        size: 8,
      },
      {
        text: '3:',
        x: 43.2,
        top: 162.12,
        size: 8,
      },
      {
        text: 'Conflicting Agreements Disclosed Under This Agreement',
        x: 43.2,
        top: 196.62,
        size: 8,
      },
      {
        text: 'The following is a list of all agreements, if any, with a current or former client, employer, or any other person or entity, that may restrict my',
        x: 43.2,
        top: 219.62,
        size: 8,
      },
      {
        text: 'ability to accept employment with Todd or my ability to recruit or engage clients or service providers on behalf of Todd, or otherwise relate or',
        x: 43.2,
        top: 231.12,
        size: 8,
      },
      {
        text: 'restrict my ability to perform my duties for Todd or any obligation I may have to Todd:',
        x: 43.2,
        top: 242.62,
        size: 8,
      },
      {
        text: '1:',
        x: 43.2,
        top: 265.62,
        size: 8,
      },
      {
        text: '2:',
        x: 43.2,
        top: 288.62,
        size: 8,
      },
      {
        text: '3:',
        x: 43.2,
        top: 311.62,
        size: 8,
      },
      {
        text: 'Except as indicated above, I have no inventions, improvements or original works to disclose pursuant to this Agreement and no agreements to',
        x: 43.2,
        top: 346.12,
        size: 8,
      },
      {
        text: 'disclose pursuant to this Agreement.',
        x: 43.2,
        top: 357.62,
        size: 8,
      },
      {
        text: 'By signing below, I acknowledge, understand, and agree to the terms of this Confidentiality and Intellectual Property Agreement; I will use',
        x: 43.2,
        top: 380.62,
        size: 8,
      },
      {
        text: 'Confidential Information only as required to perform my duties for Todd and not for my personal benefit or for the benefit of any other',
        x: 43.2,
        top: 392.12,
        size: 8,
      },
      {
        text: 'individual or entity.',
        x: 43.2,
        top: 403.62,
        size: 8,
      },
      {
        text: 'IN WITNESS WHEREOF, Todd Agriscience, Inc. and I have executed this Confidentiality and Intellectual Property Agreement as of the',
        x: 43.2,
        top: 426.62,
        size: 8,
      },
      {
        text: 'Effective Date first written below.',
        x: 43.2,
        top: 438.12,
        size: 8,
      },
      {
        text: 'Effective Date: ________________________________________',
        x: 43.2,
        top: 461.12,
        size: 8,
      },
      {
        text: 'Full Name of Employee: ________________________________________',
        x: 43.2,
        top: 484.12,
        size: 8,
      },
      {
        text: 'Employee Signature: ________________________________________',
        x: 43.2,
        top: 507.12,
        size: 8,
      },
      {
        text: 'Employer Signature: /s/ Vincent Todd',
        x: 43.2,
        top: 530.12,
        size: 8,
      },
      {
        text: 'To exercise your acceptance, do the following:',
        x: 43.2,
        top: 553.12,
        size: 8,
      },
      {
        text: '1) Fill out, sign and send back this page electronically to: ethics@toddagriscience.com. Please put “IP Agreement Acceptance” in the Subject',
        x: 43.2,
        top: 576.12,
        size: 8,
      },
      {
        text: 'Line. You must email from your registered email address.',
        x: 43.2,
        top: 587.62,
        size: 8,
      },
    ],
    rules: [
      {
        x0: 43.2,
        x1: 374.11,
        top: 53.34,
        fitToText: true,
      },
      {
        x0: 43.2,
        x1: 256.59,
        top: 202.84,
        fitToText: true,
      },
    ],
  },
];
