name: Security

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 #v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun i

      - name: Check for security vulnerabilities
        run: bun audit --audit-level=high
